# Setup
title:               ViolentTestPen
tagline:             'My CTF Writeups'
description:         'I post my CTF writeups here. Most of them are pwns'
url:                 https://violenttestpen.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Winston Ho
  url:               https://twitter.com/violenttestpen
  email:             webmaster@example.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
